import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar/Navbar";
import { AppThemeProvider } from "@/components/provider/AppThemeProvider";
import Footer from "@/components/footer/Footer";
import { BackToTop } from "@/components/button/BackToTop";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Arroziqi's Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppThemeProvider>
          <div className="max-w-7xl mx-auto relative min-h-screen overflow-x-hidden">
            <Navbar />
            {children}
            <Footer />
            <BackToTop />
          </div>
        </AppThemeProvider>
      </body>
    </html>
  );
}
